# Data Cleaning

In [2]:
import numpy as np
import pandas as pd

In [6]:
dfm=pd.read_csv(r"C:\Users\SANDESH\Downloads\ipl_dummy.csv")

In [7]:
df=dfm.copy()

In [8]:
df.head()

             Player  Team  Matches  Runs  StrikeRate  Average      Salary
0   Ruturaj Gaikwad  PBKS     12.0   892      152.59    62.47  17496572.0
1      Shubman Gill   SRH      7.0   437      173.84    42.35   8734049.0
2  Yashasvi Jaiswal  PBKS      9.0   731      179.30    28.25  29873195.0
3   Ravindra Jadeja    DC     13.0   889      127.60    65.90  11115790.0
4  Suryakumar Yadav    GT      2.0   605      137.71    70.04  19800099.0

In [9]:
df.tail()

                Player  Team  Matches  Runs  StrikeRate  Average      Salary
2045     Hardik Pandya  PBKS      4.0   725      125.59    72.31  15613891.0
2046  Suryakumar Yadav   LSG      8.0   203      180.34    72.64   6499202.0
2047      Rohit Sharma   KKR      4.0   473         NaN    50.49  26776180.0
2048   Ravindra Jadeja    MI      9.0   626      196.23    10.43  28116594.0
2049      Rohit Sharma    DC      8.0   409      107.57    55.35   7553540.0

In [10]:
df.shape

(2050, 7)

In [11]:
df.columns

Index(['Player', 'Team', 'Matches', 'Runs', 'StrikeRate', 'Average', 'Salary'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      2050 non-null   object
 1   Team        2050 non-null   object
 2   Matches     2010 non-null   float64
 3   Runs        2050 non-null   int64
 4   StrikeRate  2008 non-null   float64
 5   Average     2010 non-null   float64
 6   Salary      2010 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 112.2+ KB

In [13]:
df.describe()

           Matches         Runs   StrikeRate      Average        Salary
count  2010.000000  2050.000000  2008.000000  2010.000000  2.010000e+03
mean      7.533831   449.410244   144.739233    41.326224  1.728427e+07
std       4.008590   259.925071    31.864316    21.430872  7.463052e+06
min       1.000000     0.000000    90.100000     5.020000  5.003212e+06
25%       4.000000   216.000000   117.197500    22.617500  1.057930e+07
50%       8.000000   447.000000   143.725000    41.075000  1.716340e+07
75%      11.000000   670.750000   172.917500    59.027500  2.386237e+07
max      14.000000   900.000000   199.940000    79.920000  2.999499e+07

In [15]:
df.isnull().sum()

Player         0
Team           0
Matches       40
Runs           0
StrikeRate    42
Average       40
Salary        40
dtype: int64

### np.where(df.isnull())  returns the row and column indices of all missing (NaN) values present in the DataFrame.
    (array([6, 25]), array([2, 5]))
    Row 6, Column 2 -> Null
    Row 25, Column 5 -> Null

In [16]:
np.where(df.isnull())

(array([   6,   18,   25,   47,   81,   83,   92,   93,  114,  179,  188,
         192,  193,  196,  197,  202,  207,  207,  224,  235,  265,  287,
         315,  321,  325,  326,  351,  357,  362,  378,  396,  408,  409,
         416,  428,  433,  436,  444,  484,  520,  525,  535,  538,  540,
         544,  546,  547,  626,  634,  642,  657,  658,  692,  723,  726,
         729,  744,  751,  756,  756,  759,  771,  771,  775,  793,  794,
         798,  803,  837,  855,  875,  883,  902,  944,  960,  965,  974,
         998, 1011, 1012, 1019, 1029, 1045, 1045, 1088, 1096, 1098, 1123,
        1123, 1124, 1133, 1136, 1137, 1160, 1162, 1186, 1214, 1245, 1263,
        1290, 1337, 1350, 1380, 1398, 1408, 1415, 1425, 1448, 1448, 1454,
        1464, 1501, 1508, 1528, 1531, 1565, 1570, 1573, 1576, 1579, 1584,
        1637, 1656, 1656, 1701, 1711, 1715, 1722, 1742, 1757, 1770, 1771,
        1777, 1781, 1805, 1825, 1828, 1835, 1840, 1847, 1857, 1862, 1865,
        1874, 1883, 1888, 1899, 1911, 1915, 1916, 1918, 1920, 1924, 1926,
        1940, 1947, 1970, 1984, 1985, 1990, 2022, 2047]),
 array([2, 2, 5, 2, 6, 5, 5, 5, 2, 5, 6, 4, 5, 2, 5, 4, 2, 5, 2, 4, 4, 6,
        4, 2, 4, 4, 4, 2, 2, 2, 2, 5, 2, 4, 6, 2, 6, 5, 5, 2, 6, 2, 5, 4,
        4, 5, 5, 5, 4, 4, 2, 5, 6, 6, 2, 6, 5, 6, 5, 6, 2, 2, 6, 5, 5, 6,
        6, 5, 5, 5, 2, 5, 5, 4, 2, 5, 6, 5, 6, 6, 6, 6, 2, 5, 4, 6, 4, 2,
        6, 5, 2, 5, 4, 2, 4, 6, 5, 4, 5, 4, 4, 2, 2, 2, 2, 6, 5, 2, 4, 4,
        4, 6, 5, 6, 2, 4, 2, 4, 4, 2, 4, 6, 2, 4, 4, 5, 5, 6, 2, 6, 6, 5,
        4, 4, 6, 4, 5, 5, 6, 4, 6, 4, 4, 5, 4, 6, 2, 2, 6, 4, 4, 6, 6, 4,
        2, 6, 6, 6, 2, 6, 4, 4]))

In [17]:
df.duplicated().sum()

np.int64(50)

In [18]:
df[df.duplicated()]

                Player  Team  Matches  Runs  StrikeRate  Average      Salary
2000    Faf du Plessis    MI     13.0   363      163.78    18.41   6103183.0
2001  Yashasvi Jaiswal    MI      1.0   362      189.76    65.03  10160593.0
2002    Faf du Plessis   KKR      8.0   872      106.66    60.01   6662060.0
2003          KL Rahul   KKR     11.0    78      127.12     5.80   7859224.0
2004      Rohit Sharma   SRH     10.0   111      143.61    74.08  25321666.0
2005   Ruturaj Gaikwad   RCB     13.0    96      186.94    25.14  27197657.0
2006       Rinku Singh   CSK      8.0   846      118.61    75.93  16351514.0
2007     Hardik Pandya    MI      5.0   720      161.31    56.56  28174146.0
2008  Yashasvi Jaiswal    GT     12.0   859      101.75    38.68  27634457.0
2009    Faf du Plessis   CSK     10.0   243      166.10    49.96  23661391.0
2010    Jasprit Bumrah    GT     14.0   297      146.67    69.68  25839536.0
2011  Suryakumar Yadav    GT     10.0   735      187.75    20.70  19115000.0
2012          KL Rahul    GT      9.0   707      169.80    17.08  27891140.0
2013      Sanju Samson   RCB     13.0   844      173.55    76.30  10648035.0
2014    Jasprit Bumrah  PBKS      5.0   326      116.21    11.69  18118719.0
2015          KL Rahul   KKR      5.0   128      121.61    50.73  13897515.0
2016       Virat Kohli   CSK      2.0   557      147.79    68.00   8614670.0
2017      Shubman Gill    RR      4.0   840      134.28    35.56  14980528.0
2018    Jasprit Bumrah   LSG      8.0   507      177.46     5.05  21543597.0
2019       Rinku Singh    DC      5.0   757      145.56    16.24  18752997.0
2020    Jasprit Bumrah   LSG      1.0    82      112.39    24.68  19887035.0
2021      Sanju Samson    RR      1.0    96      199.91    20.74   7375093.0
2022      Sanju Samson   KKR      6.0    40         NaN    51.17   5866525.0
2023          KL Rahul   CSK     11.0   221      192.16    72.95  25891069.0
2024       Rinku Singh   LSG     12.0   325      182.00    66.55   7783993.0
2025  Suryakumar Yadav  PBKS      1.0   533      191.96    27.75  23325712.0
2026      Sanju Samson   CSK      8.0   723       90.40    48.39  29570283.0
2027          MS Dhoni    GT     10.0   470      137.61     8.04   8250060.0
2028          MS Dhoni    RR      1.0    35      126.72    10.88  10769537.0
2029       Virat Kohli    MI      7.0   120      125.88    25.04  27539942.0
2030      Rohit Sharma   LSG     11.0   619      122.11    11.29  28531674.0
2031  Yashasvi Jaiswal   LSG     12.0   541      198.48     9.24  14471696.0
2032       Rinku Singh   LSG     13.0   797      170.13    76.28  14094776.0
2033       Virat Kohli    GT     12.0   576      181.79    56.96  14484230.0
2034    Faf du Plessis  PBKS      3.0   194      104.66    67.77  24339070.0
2035          MS Dhoni   RCB     10.0    41      104.28    61.50   9377577.0
2036    Faf du Plessis    DC      1.0   122      101.68    50.71  23397100.0
2037          MS Dhoni    GT     13.0   444      161.33    11.25  25502779.0
2038          KL Rahul   RCB      6.0   528       99.72    13.02  28281322.0
2039    Jasprit Bumrah    GT      6.0   573      173.25    46.91  14726360.0
2040   Ravindra Jadeja   CSK     12.0   740      143.42    70.96  11210239.0
2041    Jasprit Bumrah  PBKS     14.0   529       96.43    73.42  12566169.0
2042     Hardik Pandya   RCB      1.0   125       93.87    23.75   5107042.0
2043    Jasprit Bumrah    GT      1.0   699       91.87    20.83   8041658.0
2044          KL Rahul   KKR      1.0   178      195.86    32.28  10959429.0
2045     Hardik Pandya  PBKS      4.0   725      125.59    72.31  15613891.0
2046  Suryakumar Yadav   LSG      8.0   203      180.34    72.64   6499202.0
2047      Rohit Sharma   KKR      4.0   473         NaN    50.49  26776180.0
2048   Ravindra Jadeja    MI      9.0   626      196.23    10.43  28116594.0
2049      Rohit Sharma    DC      8.0   409      107.57    55.35   7553540.0

In [19]:
df.drop_duplicates(inplace=True)

### Missing Values

#### Matches

In [21]:
df["Matches"] = df["Matches"].fillna(
    df["Matches"].median()
)

#### Strike Rate

In [23]:
df["StrikeRate"] = df["StrikeRate"].fillna(
    df["StrikeRate"].mean()
)

#### Average

In [24]:
df["Average"] = df["Average"].fillna(
    df["Average"].median()
)

#### Salary

In [26]:
df["Salary"] = df["Salary"].fillna(
    df["Salary"].median()
)

#### Verification

In [27]:
df.isnull().sum()

Player        0
Team          0
Matches       0
Runs          0
StrikeRate    0
Average       0
Salary        0
dtype: int64

### Checking Datatypes

In [29]:
df.dtypes

Player         object
Team           object
Matches       float64
Runs            int64
StrikeRate    float64
Average       float64
Salary        float64
dtype: object

#### Convert

In [31]:
df["Matches"] = df["Matches"].astype(int)

df["Salary"] = df["Salary"].astype(int)

### Salary in Lakh

In [32]:
df["Salary_Lakh"] = np.round(
    df["Salary"]/100000,
    2
)

### Runs Per Match

In [33]:
df["Runs_Per_Match"] = np.round(
    df["Runs"]/df["Matches"],
    2
)

In [35]:
df.head()

,Player,Team,Matches,Runs,StrikeRate,Average,Salary,Salary_Lakh,Runs_Per_Match
0,Ruturaj Gaikwad,PBKS,12,892,152.59,62.47,17496572,174.97,74.33
1,Shubman Gill,SRH,7,437,173.84,42.35,8734049,87.34,62.43
2,Yashasvi Jaiswal,PBKS,9,731,179.30,28.25,29873195,298.73,81.22
3,Ravindra Jadeja,DC,13,889,127.60,65.90,11115790,111.16,68.38
4,Suryakumar Yadav,GT,2,605,137.71,70.04,19800099,198.00,302.50

### Numpy Analysis

#### Highest Runs

In [41]:
np.max(df["Runs"])

900

### Standard Deviation

In [43]:
np.std(df["Runs"])

259.6331308134614

### Team Wise Analysis

In [44]:
df.groupby("Team")["Runs"].mean()  # By Runs

Team
CSK     448.252381
DC      430.928177
GT      434.138614
KKR     444.096618
LSG     432.657277
MI      428.768116
PBKS    467.034314
RCB     481.430000
RR      452.348485
SRH     480.134831
Name: Runs, dtype: float64

In [55]:
df.groupby("Team")["Salary"].mean().astype(int) # By Salary

Team
CSK     17675855
DC      17233824
GT      17024123
KKR     16305344
LSG     17702825
MI      17917928
PBKS    17749641
RCB     16882042
RR      17117065
SRH     17204023
Name: Salary, dtype: int64

### Sorting

#### Top Run Scores

In [48]:
df.sort_values(
    by="Runs",
    ascending=False
).head(10)

,Player,Team,Matches,Runs,StrikeRate,Average,Salary,Salary_Lakh,Runs_Per_Match
204,Ravindra Jadeja,KKR,11,900,103.87,14.94,17074815,170.75,81.82
297,Ruturaj Gaikwad,RR,10,899,145.51,30.39,23191663,231.92,89.90
1008,Sanju Samson,GT,14,899,127.57,15.57,27596668,275.97,64.21
1451,Ravindra Jadeja,PBKS,5,898,120.77,49.63,18074511,180.75,179.60
476,Rinku Singh,KKR,4,897,95.68,66.89,17745688,177.46,224.25
359,KL Rahul,CSK,2,897,141.45,16.89,24916048,249.16,448.50
1473,Rinku Singh,PBKS,7,896,95.26,38.64,6034549,60.35,128.00
1760,KL Rahul,PBKS,9,896,129.11,49.21,27751766,277.52,99.56
1767,David Warner,KKR,9,896,140.53,24.70,21551253,215.51,99.56
17,Sanju Samson,PBKS,4,896,139.54,66.45,14419257,144.19,224.00

#### Highest Salary

In [49]:
df.sort_values(
    by="Salary",
    ascending=False
).head(10)

,Player,Team,Matches,Runs,StrikeRate,Average,Salary,Salary_Lakh,Runs_Per_Match
1462,Ravindra Jadeja,GT,11,221,184.26,76.76,29994990,299.95,20.09
848,Shubman Gill,MI,4,291,190.05,41.69,29982913,299.83,72.75
323,MS Dhoni,PBKS,4,89,112.44,24.22,29976147,299.76,22.25
310,Suryakumar Yadav,GT,7,891,185.08,69.71,29944615,299.45,127.29
640,Shubman Gill,PBKS,12,71,198.07,58.58,29928689,299.29,5.92
1052,Suryakumar Yadav,PBKS,2,170,180.49,67.90,29924225,299.24,85.00
787,Yashasvi Jaiswal,CSK,14,333,104.34,72.73,29914208,299.14,23.79
921,KL Rahul,CSK,1,160,92.20,15.23,29904894,299.05,160.00
257,Ravindra Jadeja,KKR,6,115,112.53,65.95,29903926,299.04,19.17
1844,Yashasvi Jaiswal,RCB,9,847,143.01,69.34,29874744,298.75,94.11

In [56]:
df[df["Team"] == "RCB"]

,Player,Team,Matches,Runs,StrikeRate,Average,Salary_Lakh,Runs_Per_Match,Salary
6,Yashasvi Jaiswal,RCB,8,614,129.96,8.52,230.47,76.75,23047458
7,KL Rahul,RCB,4,734,177.33,47.47,130.96,183.50,13096173
15,KL Rahul,RCB,6,856,134.21,38.51,166.28,142.67,16628044
18,Sanju Samson,RCB,8,438,172.39,31.99,248.05,54.75,24805152
44,Ravindra Jadeja,RCB,3,656,116.66,45.25,65.06,218.67,6506440
...,...,...,...,...,...,...,...,...,...
1966,Yashasvi Jaiswal,RCB,8,13,160.77,61.66,98.74,1.62,9874010
1970,Faf du Plessis,RCB,5,131,178.21,52.15,171.73,26.20,17173443
1979,Suryakumar Yadav,RCB,6,204,131.73,43.56,233.67,34.00,23367359
1981,Yashasvi Jaiswal,RCB,5,154,157.69,38.28,209.55,30.80,20955441
1991,Virat Kohli,RCB,12,91,166.79,14.26,219.76,7.58,21976257

In [58]:
df[df["Team"] == "RCB"]["Player"].unique()

array(['Yashasvi Jaiswal', 'KL Rahul', 'Sanju Samson', 'Ravindra Jadeja',
       'David Warner', 'Virat Kohli', 'Jasprit Bumrah', 'Rohit Sharma',
       'Hardik Pandya', 'Ruturaj Gaikwad', 'Rinku Singh', 'Shubman Gill',
       'Suryakumar Yadav', 'Faf du Plessis', 'MS Dhoni'], dtype=object)

In [65]:
df[(df["Player"] == "Virat Kohli") & (df["Team"] == "RCB")].max()

Player            Virat Kohli
Team                      RCB
Matches                    14
Runs                      886
StrikeRate             193.01
Average                 73.99
Salary_Lakh            282.25
Runs_Per_Match          884.0
Salary               28224942
dtype: object

### Target Column At End

In [50]:
salary = df.pop("Salary")

df["Salary"] = salary

In [53]:
df.isnull().sum().any()

np.False_

In [54]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.shape

(2000, 9)

In [66]:
df.to_csv("Cleaned_IPL.csv",index=False)
print("Data Saved Successfully")

Data Saved Successfully