In [1]:
import pandas as pd

In [2]:
dfm=pd.read_csv(r"C:\Users\SANDESH\Downloads\hospitality_dirty.csv")

In [3]:
df=dfm.copy()

In [4]:
df.head()

,Guest_ID,Guest_Name,Hotel_Name,City,Room_Type,Nights_Stayed,Room_Rate,Food_Bill,Rating,Booking_Source,CheckIn_Date,Total_Bill
0,1001,Rohan Singh,Royal Inn,Delhi,Suite,2,4580,6033.0,3.4,MakeMyTrip,2025-09-14,15193.0
1,1002,Anjali Gupta,City Palace,Bangalore,Standard,2,10146,869.0,4.3,Booking.com,2025-06-05,21161.0
2,1003,Karan Kulkarni,Comfort Hub,Hyderabad,Executive,4,10243,5526.0,4.4,Booking.com,2025-04-23,46498.0
3,1004,Priya Rao,City Palace,Mumbai,Suite,7,11553,7741.0,3.5,Agoda,2025-11-14,88612.0
4,1005,Rohan Rao,Elite Suites,Chennai,Standard,5,11386,5165.0,2.5,Goibibo,2025-02-16,62095.0

In [5]:
df.shape

(2050, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Guest_ID        2050 non-null   int64
 1   Guest_Name      2050 non-null   object
 2   Hotel_Name      2050 non-null   object
 3   City            2050 non-null   object
 4   Room_Type       2050 non-null   object
 5   Nights_Stayed   2050 non-null   int64
 6   Room_Rate       2050 non-null   int64
 7   Food_Bill       2010 non-null   float64
 8   Rating          2010 non-null   float64
 9   Booking_Source  2010 non-null   object
 10  CheckIn_Date    2050 non-null   object
 11  Total_Bill      2050 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 192.3+ KB

In [7]:
df.describe()

,Guest_ID,Nights_Stayed,Room_Rate,Food_Bill,Rating,Total_Bill
count,2050.000000,2050.000000,2050.000000,2010.000000,2010.000000,2050.000000
mean,2002.148780,3.952195,6966.553171,3917.259701,3.739005,31608.773659
std,577.141537,2.047903,2907.876233,2301.304086,0.721325,19546.513613
min,1001.000000,1.000000,2007.000000,2.000000,2.500000,2317.000000
25%,1504.250000,2.000000,4365.250000,1887.250000,3.100000,15625.250000
50%,2001.500000,4.000000,7024.000000,3881.000000,3.700000,27084.500000
75%,2501.750000,6.000000,9429.750000,5807.000000,4.300000,44297.250000
max,3000.000000,7.000000,11996.000000,7999.000000,5.000000,91766.000000

### Missing Values

In [10]:
df.isnull().sum()

Guest_ID           0
Guest_Name         0
Hotel_Name         0
City               0
Room_Type          0
Nights_Stayed      0
Room_Rate          0
Food_Bill         40
Rating            40
Booking_Source    40
CheckIn_Date       0
Total_Bill         0
dtype: int64

#### Numrical Values Food_Bill

In [12]:
df["Food_Bill"] = df["Food_Bill"].fillna(
    df["Food_Bill"].median()
)

#### Categorical Values Booking source

In [14]:
df["Booking_Source"] = df["Booking_Source"].fillna(
    df["Booking_Source"].mode()[0]
)

### Not Null Values

In [15]:
df.notnull().sum()

Guest_ID          2050
Guest_Name        2050
Hotel_Name        2050
City              2050
Room_Type         2050
Nights_Stayed     2050
Room_Rate         2050
Food_Bill         2050
Rating            2010
Booking_Source    2050
CheckIn_Date      2050
Total_Bill        2050
dtype: int64

### Duplicates

In [16]:
df.duplicated().sum()

np.int64(50)

In [18]:
df.drop_duplicates(inplace=True)

### Datatypes

In [21]:
df["CheckIn_Date"] = pd.to_datetime(
    df["CheckIn_Date"]
)

In [43]:
df["Rating"] = df["Rating"].astype(float)

In [20]:
df.dtypes

Guest_ID            int64
Guest_Name         object
Hotel_Name         object
City               object
Room_Type          object
Nights_Stayed       int64
Room_Rate           int64
Food_Bill         float64
Rating            float64
Booking_Source     object
CheckIn_Date       object
Total_Bill        float64
dtype: object

### String Cleaning

In [23]:
df["City"] = df["City"].str.strip().str.title()

### Features

In [24]:
df["Total_Bill"] = (
    df["Room_Rate"] * df["Nights_Stayed"]
    + df["Food_Bill"]
)

#### Cost Per Night

In [26]:
df["Cost_Per_Night"] = (
    df["Total_Bill"]
    / df["Nights_Stayed"]
)

### Numpy Functions

In [28]:
df["Total_Bill"].agg(["min", "max", "mean", "median", "sum"]).round(2)

min           2317.00
max          91766.00
mean         31516.46
median       27084.50
sum       63032915.00
Name: Total_Bill, dtype: float64

#### Group By Analysis

In [29]:
df.groupby("City")["Rating"].mean() # Avarage Rating By City

City
Bangalore    3.758278
Chennai      3.750760
Delhi        3.761280
Hyderabad    3.700888
Mumbai       3.747159
Pune         3.736334
Name: Rating, dtype: float64

In [30]:
df.groupby("Hotel_Name")["Total_Bill"].sum() # Revenue By Hotel

Hotel_Name
City Palace     10180148.0
Comfort Hub     10574100.0
Elite Suites    10779116.0
Grand Stay      11227941.0
Ocean View      10238114.0
Royal Inn       10033496.0
Name: Total_Bill, dtype: float64

### Sorting
    Top Customers

In [33]:
df = df.sort_values(by="Total_Bill", ascending=False)
df.head()

,Guest_ID,Guest_Name,Hotel_Name,City,Room_Type,Nights_Stayed,Room_Rate,Food_Bill,Rating,Booking_Source,CheckIn_Date,Total_Bill,Cost_Per_Night
639,1640,Anjali Patil,Grand Stay,Bangalore,Deluxe,7,11984,7878.0,3.3,Walk-in,2025-07-27,91766.0,13109.428571
1278,2279,Pooja Sharma,Royal Inn,Mumbai,Deluxe,7,11916,7909.0,2.6,Booking.com,2025-12-06,91321.0,13045.857143
1465,2466,Vikas Sharma,Grand Stay,Delhi,Executive,7,11978,7401.0,2.6,Booking.com,2025-10-12,91247.0,13035.285714
1065,2066,Rohan Kulkarni,Royal Inn,Bangalore,Deluxe,7,11862,7959.0,2.9,Goibibo,2025-06-19,90993.0,12999.000000
1396,2397,Anjali Verma,City Palace,Delhi,Deluxe,7,11780,6968.0,4.5,Booking.com,2025-07-18,89428.0,12775.428571

#### Date Analysis

In [35]:
df["Month"] = df["CheckIn_Date"].dt.year  # Year Extract

In [36]:
df["Month"] = df["CheckIn_Date"].dt.month    # Month Extract

In [37]:
df["Weekday"] = df["CheckIn_Date"].dt.day_name() # Weekday Extraction

In [38]:
df.head()

,Guest_ID,Guest_Name,Hotel_Name,City,Room_Type,Nights_Stayed,Room_Rate,Food_Bill,Rating,Booking_Source,CheckIn_Date,Total_Bill,Cost_Per_Night,Month,Weekday
639,1640,Anjali Patil,Grand Stay,Bangalore,Deluxe,7,11984,7878.0,3.3,Walk-in,2025-07-27,91766.0,13109.428571,7,Sunday
1278,2279,Pooja Sharma,Royal Inn,Mumbai,Deluxe,7,11916,7909.0,2.6,Booking.com,2025-12-06,91321.0,13045.857143,12,Saturday
1465,2466,Vikas Sharma,Grand Stay,Delhi,Executive,7,11978,7401.0,2.6,Booking.com,2025-10-12,91247.0,13035.285714,10,Sunday
1065,2066,Rohan Kulkarni,Royal Inn,Bangalore,Deluxe,7,11862,7959.0,2.9,Goibibo,2025-06-19,90993.0,12999.000000,6,Thursday
1396,2397,Anjali Verma,City Palace,Delhi,Deluxe,7,11780,6968.0,4.5,Booking.com,2025-07-18,89428.0,12775.428571,7,Friday

In [40]:
df.columns

Index(['Guest_ID', 'Guest_Name', 'Hotel_Name', 'City', 'Room_Type',
       'Nights_Stayed', 'Room_Rate', 'Food_Bill', 'Rating', 'Booking_Source',
       'CheckIn_Date', 'Total_Bill', 'Cost_Per_Night', 'Month', 'Weekday'],
      dtype='object')

In [42]:
df.shape

(2000, 15)

In [45]:
df.to_csv("Cleaned.csv",index=False)
print("Data Saved Succesufully")

Data Saved Succesufully