In [1]:
import pandas as pd

In [2]:
dfm=pd.read_csv(r"C:\Users\SANDESH\Downloads\laptopData.csv")

In [367]:
df=dfm.copy()
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [368]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [369]:
df.describe()

        Unnamed: 0          Price
count  1273.000000    1273.000000
mean    652.674784   59955.814073
std     376.493027   37332.251005
min       0.000000    9270.720000
25%     327.000000   31914.720000
50%     652.000000   52161.120000
75%     980.000000   79333.387200
max    1302.000000  324954.720000

In [370]:
df.shape

(1303, 12)

In [371]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

### Missing Values

In [372]:
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

### Count In Percentage

In [373]:
(df.isnull().sum()/len(df))*100

Unnamed: 0          2.302379
Company             2.302379
TypeName            2.302379
Inches              2.302379
ScreenResolution    2.302379
Cpu                 2.302379
Ram                 2.302379
Memory              2.302379
Gpu                 2.302379
OpSys               2.302379
Weight              2.302379
Price               2.302379
dtype: float64

### Duplicates Record

In [374]:
df.duplicated().sum()

np.int64(29)

In [375]:
df.duplicated().any()

np.True_

#### Removing Duplicates

In [376]:
df.drop_duplicates(inplace=True)

In [377]:
df.duplicated().any()

np.False_

#### Remove Unnecessary Column

In [378]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

### Fill Null Values

In [381]:
df["Company"].fillna(df["Company"].mode(), inplace=True)

In [382]:
df.isnull().sum()

Company             0
TypeName            1
Inches              1
ScreenResolution    1
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [383]:
df.dropna(inplace=True)

In [384]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [390]:
df["Inches"] = df["Inches"].fillna(
    df["Inches"].median()
)

### Fix Data Types

### Inches

In [391]:
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 31.6, 17. , 15. , 14.1,
       11.3, 10.1])

In [392]:
df["Inches"] = pd.to_numeric(
    df["Inches"],
    errors="coerce"
)                        # ? == nan convert

In [393]:
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 31.6, 17. , 15. , 14.1,
       11.3, 10.1])

In [394]:
df["Inches"] = df["Inches"].astype(float)

### Formating Values

#### Ram Column

In [395]:
df["Ram"] = df["Ram"].str.replace("GB"," GB")

#### Weight Column

In [396]:
df["Weight"] = df["Weight"].str.replace("kg"," KG")

### Cpu Column
     r'(\d+\.\d+)GHz' is a Regular Expression (Regex) pattern used to extract

In [397]:
df["Cpu_Brand"] = df["Cpu"].apply(
    lambda x: x.split()[0] if pd.notna(x) else None
)

In [398]:
df["Cpu_Speed"] = df["Cpu"].str.extract(r'(\d+\.\d)')[0] + " GHz"

df["Cpu_Type"] = df["Cpu"].str.extract(r'(Core i[3579])')

In [434]:
df["Cpu_Speed"] = df["Cpu_Speed"].fillna(0)

df["Cpu_Type"] = df["Cpu_Type"].fillna(df["Cpu_Type"].mode()[0])

In [399]:
df.drop(["Cpu"], axis=1, inplace=True)

### Screen Resolution

In [400]:
df["Display_Type"] = df["ScreenResolution"].str.extract(r'^(.*)\s(\d+x\d+)$')[0]

In [401]:
df["Resolution"] = df["ScreenResolution"].str.extract(r'(\d+x\d+)')

In [402]:
df["X_res"] = df["Resolution"].apply(
    lambda x: x.split("x")[0] if pd.notna(x) else None
)

df["Y_res"] = df["Resolution"].apply(
    lambda x: x.split("x")[1] if pd.notna(x) else None
)

#### Calculate PPI (Professional Feature Engineering)
    Pixel Per Inch

In [403]:
 df["X_res"] = pd.to_numeric(df["X_res"], errors="coerce")
df["Y_res"] = pd.to_numeric(df["Y_res"], errors="coerce")
df["Inches"] = pd.to_numeric(df["Inches"], errors="coerce")

In [404]:
import numpy as np

df["PPI"] = (
    np.sqrt(df["X_res"]**2 + df["Y_res"]**2)
    / df["Inches"]
)
df["PPI"] = df["PPI"].round(3)

In [405]:
df["Display_Type"] = df["ScreenResolution"].apply(
    lambda x: "Unknown" if pd.isna(x)
    else "Retina" if "Retina Display" in x
    else "IPS" if "IPS Panel" in x
    else "Full HD" if "Full HD" in x
    else "Quad HD+" if "Quad HD+" in x
    else "Standard"
)

In [406]:
df.drop(["ScreenResolution"], axis=1, inplace=True)

### Clean Memory Column

In [407]:
df["Storage_Type"] = df["Memory"].str.extract(
    r'(SSD|HDD|Flash Storage|Hybrid)'
)

In [408]:
df["Storage_Size"] = df["Memory"].str.extract(r'(\d+\s?(?:GB|TB))')[0]

df["Storage_Size"] = (
    df["Storage_Size"]
    .str.replace("GB", " GB")
    .str.replace("TB", " TB")
    .str.strip()
)

In [436]:
df.fillna({
    "Storage_Type": df["Storage_Type"].mode()[0],
    "Storage_Size": df["Storage_Size"].mode()[0],
  
}, inplace=True)

In [409]:
df.drop(["Memory"], axis=1, inplace=True)

### Gpu column

In [410]:
df["Gpu_Brand"] = df["Gpu"].str.extract(r'^(Intel|Nvidia|AMD)')

In [411]:
df["Gpu_Model"] = df["Gpu"].str.replace(
    r'^(Intel|Nvidia|AMD)\s+',
    '',
    regex=True
)

In [438]:
df["Gpu_Brand"] = df["Gpu_Brand"].fillna(df["Gpu_Brand"].mode()[0])

In [412]:
df.drop(["Gpu"], axis=1, inplace=True)

### Clean Operating System Column

#### Group Categories

In [413]:
def os_category(x):
    if pd.isna(x):
        return "Unknown"
    elif "Windows" in x:
        return "Windows"
    elif "Mac" in x or "macOS" in x:
        return "Mac"
    elif "Linux" in x:
        return "Linux"
    else:
        return "Other"

df["OS"] = df["OpSys"].apply(os_category)

In [414]:
df.drop(["OpSys"], axis=1, inplace=True)

### Price Column

In [416]:
df["Price"] = df["Price"].astype(float)
df["Price"] = df["Price"].round(2)

In [415]:
df.shape

(1273, 19)

In [417]:
price_col = df.pop("Price")
df.insert(len(df.columns), "Price", price_col)

In [418]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'Ram', 'Weight', 'Cpu_Brand',
       'Cpu_Speed', 'Cpu_Type', 'Display_Type', 'Resolution', 'X_res', 'Y_res',
       'PPI', 'Storage_Type', 'Storage_Size', 'Gpu_Brand', 'Gpu_Model', 'OS',
       'Price'],
      dtype='object')

In [430]:
df.head(10)

,Company,TypeName,Inches,Ram,Weight,Cpu_Brand,Cpu_Speed,Cpu_Type,Display_Type,Resolution,X_res,Y_res,PPI,Storage_Type,Storage_Size,Gpu_Brand,Gpu_Model,OS,Price
0,Apple,Ultrabook,13.3,8 GB,1.37 KG,Intel,2.3 GHz,Core i5,Retina,2560x1600,2560,1600,226.983,SSD,128 GB,Intel,Iris Plus Graphics 640,Mac,71378.68
1,Apple,Ultrabook,13.3,8 GB,1.34 KG,Intel,1.8 GHz,Core i5,Standard,1440x900,1440,900,127.678,Flash Storage,128 GB,Intel,HD Graphics 6000,Mac,47895.52
2,HP,Notebook,15.6,8 GB,1.86 KG,Intel,2.5 GHz,Core i5,Full HD,1920x1080,1920,1080,141.212,SSD,256 GB,Intel,HD Graphics 620,Other,30636.00
3,Apple,Ultrabook,15.4,16 GB,1.83 KG,Intel,2.7 GHz,Core i7,Retina,2880x1800,2880,1800,220.535,SSD,512 GB,AMD,Radeon Pro 455,Mac,135195.34
4,Apple,Ultrabook,13.3,8 GB,1.37 KG,Intel,3.1 GHz,Core i5,Retina,2560x1600,2560,1600,226.983,SSD,256 GB,Intel,Iris Plus Graphics 650,Mac,96095.81
5,Acer,Notebook,15.6,4 GB,2.1 KG,AMD,NaN,NaN,Standard,1366x768,1366,768,100.455,HDD,500 GB,AMD,Radeon R5,Windows,21312.00
6,Apple,Ultrabook,15.4,16 GB,2.04 KG,Intel,2.2 GHz,Core i7,Retina,2880x1800,2880,1800,220.535,Flash Storage,256 GB,Intel,Iris Pro Graphics,Mac,114017.60
7,Apple,Ultrabook,13.3,8 GB,1.34 KG,Intel,1.8 GHz,Core i5,Standard,1440x900,1440,900,127.678,Flash Storage,256 GB,Intel,HD Graphics 6000,Mac,61735.54
8,Asus,Ultrabook,14.0,16 GB,1.3 KG,Intel,1.8 GHz,Core i7,Full HD,1920x1080,1920,1080,157.351,SSD,512 GB,Nvidia,GeForce MX150,Windows,79653.60
9,Acer,Ultrabook,14.0,8 GB,1.6 KG,Intel,1.6 GHz,Core i5,IPS,1920x1080,1920,1080,157.351,SSD,256 GB,Intel,UHD Graphics 620,Windows,41025.60

In [443]:
df.isnull().sum().any()

np.False_

In [444]:
df.to_csv("Laptop_Cleaned.csv",index=False)
print("Data Saved Successfully")

Data Saved Successfully